routes:
  home:
    path: /
    controller: App\Controllers\HomeController::index
    methods: [GET]

  about:
    path: /about
    controller: App\Controllers\HomeController::about
    methods: [GET]

  setup:
    path: /setup
    controller: App\Controllers\SetupController::index
    methods: [GET]

  admin_home:
    path: /admin
    controller: App\Controllers\Admin\HomeController::index
    methods: [GET]

  admin_login:
    path: /admin/login
    controller: App\Controllers\Admin\SecurityController::login
    methods: [GET]
