routes:
  home:
    path: /
    controller: App\Controllers\HomeController::index
    methods: [GET]

  about:
    path: /about
    controller: App\Controllers\HomeController::about
    methods: [GET]

  setup:
    path: /setup
    controller: App\Controllers\SetupController::index
    methods: [GET]

  admin_home:
    path: /admin
    controller: App\Controllers\Admin\HomeController::index
    methods: [GET]

  admin_login:
    path: /admin/login
    controller: App\Controllers\Admin\SecurityController::login
    methods: [GET]

  admin_logout:
    path: /admin/logout
    controller: App\Controllers\Admin\SecurityController::logout
    methods: [GET]

  admin_login_submit:
    path: /admin/login/submit
    controller: App\Controllers\Admin\SecurityController::login_submit
    methods: [POST]
  
  admin_change_password:
    path: /admin/change-password
    controller: App\Controllers\Admin\SecurityController::change_password
    methods: [GET]

  admin_change_password_submit:
    path: /admin/change-password/submit
    controller: App\Controllers\Admin\SecurityController::change_password_submit
    methods: [POST]
